// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type CommentsConnection struct {
	Edges    []*CommentsEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type CommentsEdge struct {
	Cursor         string   `json:"cursor"`
	HasSubComments bool     `json:"hasSubComments"`
	Node           *Comment `json:"node,omitempty"`
}

type Content struct {
	ID              int                 `json:"id"`
	Title           *string             `json:"title,omitempty"`
	Content         *string             `json:"content,omitempty"`
	CommentsEnabled *bool               `json:"commentsEnabled,omitempty"`
	AuthorUUID      *string             `json:"authorUuid,omitempty"`
	CreatedAt       *string             `json:"createdAt,omitempty"`
	Comments        *CommentsConnection `json:"comments,omitempty"`
}

type GetCommentsInput struct {
	PostID int `json:"postId"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   int    `json:"postId"`
	ParentID *int   `json:"parentId,omitempty"`
	Content  string `json:"content"`
}

type NewPost struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
}

type Query struct {
}

type RefreshInput struct {
	Refresh string `json:"refresh"`
}

type RegisterInput struct {
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	Password  string `json:"password"`
}

type Subscription struct {
}

type User struct {
	UUID      string `json:"uuid"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
}
