// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	AuthToken *AuthToken `json:"auth_token"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type Comment struct {
	ID         string  `json:"id"`
	PostID     int     `json:"post_id"`
	ParentID   *int    `json:"parent_id,omitempty"`
	AuthorUUID string  `json:"author_uuid"`
	Content    string  `json:"content"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  *string `json:"updated_at,omitempty"`
}

type GetCommentsInput struct {
	PostID string `json:"post_id"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewComment struct {
	Content string `json:"content"`
}

type NewPost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Query struct {
}

type RefreshInput struct {
	Refresh string `json:"refresh"`
}

type RegisterInput struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	Password  string `json:"password"`
}

type User struct {
	UUID      string `json:"uuid"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
}
